publish_mode: editorial_workflow
media_folder: "images/uploads"
public_folder: "/images/uploads"
backend:
    name: git-gateway
    branch: master
collections:
    - name: "blog"
      label: "Blog"
      folder: "_posts/blog"
      create: true
      slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
      fields:
          - {label: "Layout", name: "layout", widget: "hidden", default: "blog"}
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Published", name: "published", widget: "boolean", default: false}
          - {label: "Published Date", name: "date", widget: "datetime"}
          - {label: "Category", name: "category", widget: "string"}
          - {label: "Featured Image", name: "thumbnail", widget: "image"}
